apiVersion: v1	
kind: Service	
metadata:	
  namespace: burnham
  name: nginx
  labels:
    somelabel: "somevalue"
    # {{- toYaml .Values.labels | nindent 4 }}
spec:	
  ports:	
  - port: 80	
    targetPort: 80	
  selector:	
    app: nginx

